### PR TITLE
Level Modifier and Force Fully Evolved, no random Trainer

### PR DESCRIPTION
**Pull request by camreonkel**
Level Modifier and Force Fully Evolved can be done without having to randomize trainer pokemon. The changes however do not show up in the log...

### CODE REVIEW

**Comment by ArtaiosGreybark** [comment]
This feature would be very nice.

**Comment by ATimmeh33** [comment]
@ArtaiosGreybark I have this branch compiled, do you still require it?

**Comment by doms777** [comment]
can someone help me if I change the files in the source code, it works but I get errors in Gen1-5RomHandler``

**Comment by modernretrocoder** [comment]
@ATimmeh33 Could you send me an executable randomizer with these modifications please? I changed the source code exactly as @camreonkel did, however I have no clue how to create an actual executable version of the randomizer with the source code.

**Comment by ArtaiosGreybark** [comment]
@ATimmeh33: Yes, that would be very kind :)

**Comment by modernretrocoder** [comment]
Or would someone be able to tell me how to run it with visual studio 2019? If that’s even possible?

**Comment by RCTMASTA** [comment]
VS2019 doesn't support Java. You need Eclipse or another Java-supporting IDE in order to compile.

**Comment by ATimmeh33** [comment]
@ArtaiosGreybark  @modernretrocoder I'll send the both of you a message with this compiled branch when I get home from work in 6-7 hours.

**Comment by modernretrocoder** [comment]
@ATimmeh33 Thanks a lot, I’ll be sure to look into how to use Eclipse for myself later too. I probably won’t be able to reply as soon as you send it since I’ve got college and work for the next 10 hours, but I will as soon as I can.

**Comment by ATimmeh33** [comment]
> @ATimmeh33 Thanks a lot, I’ll be sure to look into how to use Eclipse for myself later too. I probably won’t be able to reply as soon as you send it since I’ve got college and work for the next 10 hours, but I will as soon as I can.

Visual Studio Code supports Java

**Comment by ATimmeh33** [comment]
[CustomRandomizer.zip](https://github.com/Dabomstew/universal-pokemon-randomizer/files/3217899/CustomRandomizer.zip)

@ArtaiosGreybark @modernretrocoder Enjoy

**Comment by modernretrocoder** [comment]
@ATimmeh33 Thank you so much, I haven't played Pokemon Platinum since I was a kid and I've wanted to experience the base game again with a hard mode for a while, so I really appreciate it. (Also special thanks to @Dabomstew for creating the UPR and @camreonkel for improving the Trainer code so that it can be used for this purpose of course.)

**Comment by Favega89** [comment]
@ATimmeh33 Hi , could you send me this branch compiled too ?

**Comment by rguinz** [comment]
Anyone know how I would do this for myself?

**Comment by Destinycallsyou** [comment]
hey i would love to have this aswell, i was looking for this option for a while now, coudnt find it, random pokemon are well, too random for my taste X), much love destiny calls you

**Comment by Destinycallsyou** [comment]
i love you all beautifull people!!!

**Comment by Destinycallsyou** [comment]
@rguinz @Favega89 he posted a dl link already

**Comment by Scotty7298** [comment]
@ATimmeh33 Thank you for the randomizer with non-random Trainer level adjustments! Is there a way to raise wild pokemon levels? Specifically I want to do a HG/SS replay, and the trainer leveling without randomization helps, but there's only so many trainers and the rematch system is quite annoying - the level curve is even worse if you still have to grind on low level wild 'mons just to fight trainers.

**Comment by ATimmeh33** [comment]
> 
> 
> @ATimmeh33 Thank you for the randomizer with non-random Trainer level adjustments! Is there a way to raise wild pokemon levels? Specifically I want to do a HG/SS replay, and the trainer leveling without randomization helps, but there's only so many trainers and the rematch system is quite annoying - the level curve is even worse if you still have to grind on low level wild 'mons just to fight trainers.

I don't think so, you'd have to change the code and compile.

**Pull request closed without merging**
